title: Sayan Chakraborty
logo: /assets/img/headshot.jpg
description: Data Scientist with 6+ years of experience in R&D analytics, specializing in leveraging healthcare datasets and data science techniques to deliver insights and solve business challenges for leading pharmaceutical firms.
theme: jekyll-theme-minimal
