title: Sayan Chakraborty
logo: /assets/img/headshot.jpg
description: Data Scientist with 4+ years of experience in data science and analytics within Research and Development. My focus area involves utilizing real-world healthcare datasets and data science methodologies to generate insights and solve business problems for top pharmaceutical companies.
theme: jekyll-theme-minimal
